version: '2'
services:
  app:
    image: machu/pukiwiki
    volumes:
      - /home/core/var/pukiwiki-data:/var/pukiwiki
    environment:
      - VIRTUAL_HOST=wolfbbs.jp
      - LETSENCRYPT_HOST=wolfbbs.jp
      - LETSENCRYPT_EMAIL=kmachu@gmail.com
    restart: always
networks:
  default:
    external:
      name: nginx-proxy
