source 'https://rubygems.org'

# use trunk
gem 'tdiary', git: 'https://github.com/tdiary/tdiary-core.git'
gem 'tdiary-contrib', git: 'https://github.com/tdiary/tdiary-contrib.git'

# enable GFM style
gem 'tdiary-style-gfm'

gem 'puma'
gem 'newrelic_rpm'
gem 'oga'
gem 'rake'

gem 'twitter-text', '1.14.2'
