app:
  image: machu/tdiary
  volumes:
    - /home/core/var/tdiary/data:/usr/src/app/data
  environment:
    - VIRTUAL_HOST=www.machu.jp
    - RACK_ENV=production
    - NEW_RELIC_LICENSE_KEY
  restart: always
