app:
  build: app
  volumes:
    - tdiary-data:/usr/src/app/data
    - tdiary-public:/usr/src/app/public
  environment:
    - RACK_ENV
    - NEW_RELIC_LICENSE_KEY
  restart: always

web:
  build: web
  ports:
    - 80:80
  links:
    - app
  volumes_from:
    - app
  environment:
    - VIRTUAL_HOST=staging.machu.jp
  restart: always
