mongodb:
  image: mongo:latest
  restart: always

memcached:
  image: memcached:latest
  restart: always

app:
  image: tdiary/rpaproxy-sinatra
  links:
    - mongodb
    - memcached
  environment:
    - RACK_ENV=production
    - MEMCACHE_SERVERS=memcached:11211
    - TWITTER_KEY
    - TWITTER_SECRET
    - VIRTUAL_HOST=rpaproxy.machu.jp,rpaproxy.tdiary.org
  restart: always
